package com.dan190.covfefe.Util;

/**
 * Created by david on 2017-09-16.
 */

public class GroupUtils {

//    myRef.setValue("Hello, World!");

    public void init_user(){
//        // Generate a reference to a new location and add some data using push()
//        var newPostRef = postsRef.push({
//                author: "gracehop",
//                title: "Announcing COBOL, a New Programming Language"
//        });
//        // Get the unique ID generated by push() by accessing its key
//                var postID = newPostRef.key;
    }

    public void modify_user_fcm_id(){

    }

    public void start_group(String group_name, int user_id){

    }

    public void join_group(int group_id, int user_id){

    }
}
